# 08_figs_expression_plotnine.py —— Fig1A-E + Fig2A-E（统一字体重渲 + 新增2D/2E）
# 数据: raw_data/01,03,04,05,15,16,07,08,10,02   用法: python3 08...py <干实验分析目录> <step>
import sys, os, re
import pandas as pd, numpy as np
from scipy.stats import mannwhitneyu, kruskal, spearmanr, ttest_ind
from plotnine import *
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from figstyle import setup_font, TH, NPG

base = sys.argv[1]; step = sys.argv[2] if len(sys.argv)>2 else "all"
rd = os.path.join(base,"raw_data"); fig = os.path.join(base,"figures", "子图原文件"); os.makedirs(fig, exist_ok=True)
FAM = setup_font(base); T = TH(FAM)
def sv(p,name,w,h):
    p.save(os.path.join(fig,name+".png"), width=w, height=h, dpi=300, verbose=False)
    p.save(os.path.join(fig,name+".pdf"), width=w, height=h, verbose=False)
def pfmt(p): return f"p = {p:.2e}" if p<0.001 else f"p = {p:.3f}"
print("font:", FAM)

if step in ("all","f1a"):
    d = pd.read_csv(os.path.join(rd,"01_TCGA_GTEx_LONP1_expression_tumor_vs_normal.csv"))
    w = mannwhitneyu(d.loc[d.group=="Tumor","LONP1_log2TPM"], d.loc[d.group=="Normal","LONP1_log2TPM"])
    d["g"] = pd.Categorical(d.group, ["Normal","Tumor"])
    n_n, n_t = (d.group=="Normal").sum(), (d.group=="Tumor").sum()
    p = (ggplot(d, aes("g","LONP1_log2TPM",fill="g")) + geom_violin(style="full", size=0.4, alpha=0.6)
         + geom_boxplot(width=0.18, outlier_shape="", alpha=0.9, size=0.5)
         + scale_fill_manual(values=[NPG["blue"],NPG["red"]])
         + scale_x_discrete(labels=[f"Normal\n(n={n_n})", f"Tumor\n(n={n_t})"])
         + labs(x="", y="LONP1 expression, log2(TPM+0.001)", title="TCGA-CESC + GTEx")
         + annotate("text", x=1.5, y=d.LONP1_log2TPM.max()+0.25, label=pfmt(w.pvalue), size=10, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig1A_TCGA_GTEx_expression",3.2,3.8); print("1A")

if step in ("all","f1bcd"):
    d4 = pd.read_csv(os.path.join(rd,"04_GSE9750_LONP1_209017_s_at.csv"))
    d4 = d4[d4.group!="cellline"].copy(); d4["l2"] = np.log2(d4.value_MAS5)
    w4 = mannwhitneyu(d4.loc[d4.group=="cancer","l2"], d4.loc[d4.group=="normal","l2"])
    d4["g"] = pd.Categorical(d4.group, ["normal","cancer"])
    p = (ggplot(d4, aes("g","l2",fill="g")) + geom_boxplot(width=0.55, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.15, size=1.1, alpha=0.45)
         + scale_fill_manual(values=[NPG["blue"],NPG["red"]])
         + scale_x_discrete(labels=[f"Normal\n(n={(d4.group=='normal').sum()})", f"Cancer\n(n={(d4.group=='cancer').sum()})"])
         + labs(x="", y="LONP1, log2(MAS5 signal)", title="GSE9750")
         + annotate("text", x=1.5, y=d4.l2.max()+0.3, label=pfmt(w4.pvalue), size=10, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig1B_GSE9750_expression",3.0,3.8)
    d5 = pd.read_csv(os.path.join(rd,"05_GSE7803_LONP1_209017_s_at.csv"))
    w5 = mannwhitneyu(d5.loc[d5.group=="scc","value_log2"], d5.loc[d5.group=="normal","value_log2"])
    d5["g"] = pd.Categorical(d5.group, ["normal","hsil","scc"])
    ns = d5.group.value_counts()
    p = (ggplot(d5, aes("g","value_log2",fill="g")) + geom_boxplot(width=0.55, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.15, size=1.1, alpha=0.45)
         + scale_fill_manual(values=[NPG["blue"],NPG["salmon"],NPG["red"]])
         + scale_x_discrete(labels=[f"Normal\n(n={ns['normal']})", f"HSIL\n(n={ns['hsil']})", f"SCC\n(n={ns['scc']})"])
         + labs(x="", y="LONP1, log2 expression", title="GSE7803")
         + annotate("text", x=2, y=d5.value_log2.max()+0.15, label="SCC vs Normal "+pfmt(w5.pvalue), size=9, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig1C_GSE7803_expression",3.4,3.8)
    d3 = pd.read_csv(os.path.join(rd,"03_GSE63514_LONP1_209017_s_at.csv"))
    w3 = mannwhitneyu(d3.loc[d3.group=="Cancer","value_log2norm"], d3.loc[d3.group=="Normal","value_log2norm"])
    d3["g"] = pd.Categorical(d3.group, ["Normal","CIN1","CIN2","CIN3","Cancer"])
    p = (ggplot(d3, aes("g","value_log2norm",fill="g")) + geom_boxplot(width=0.6, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.15, size=1.0, alpha=0.45)
         + scale_fill_manual(values=[NPG["blue"],NPG["teal"],NPG["salmon"],NPG["purple"],NPG["red"]])
         + labs(x="", y="LONP1, log2 expression", title="GSE63514 (LCM epithelium)")
         + annotate("text", x=3, y=d3.value_log2norm.max()+0.4, label="Cancer vs Normal "+pfmt(w3.pvalue), size=9, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig1D_GSE63514_expression",4.6,3.8); print("1BCD")

if step in ("all","f1e"):
    dat = pd.read_csv(os.path.join(rd,"15_pancancer_LONP1_per_sample.csv"))
    st = pd.read_csv(os.path.join(rd,"16_pancancer_LONP1_stats.csv"))
    st["sig"] = pd.cut(st.padj, [-np.inf,0.001,0.01,0.05,np.inf], labels=["***","**","*",""]).astype(str).replace("nan","")
    dat["grp"] = pd.Categorical(dat.grp, ["Normal","Tumor"])
    ymax = dat.LONP1.max()
    p = (ggplot(dat, aes("type","LONP1",fill="grp"))
         + geom_boxplot(width=0.68, outlier_size=0.25, outlier_alpha=0.25, size=0.3)
         + scale_fill_manual(values={"Tumor":NPG["red"],"Normal":NPG["blue"]})
         + labs(fill="")
         + geom_text(data=st, mapping=aes(x="type", label="sig"), y=ymax+0.25, inherit_aes=False, size=8, family=FAM)
         + labs(x="", y="LONP1, log2(TPM+0.001)", title="LONP1 across TCGA cancer types (tumors vs GTEx+TCGA normal)")
         + coord_cartesian(ylim=(2, ymax+0.5))
         + T + theme(axis_text_x=element_text(rotation=55, ha="right", size=8.5, family=FAM), legend_position="top"))
    sv(p,"Fig1E_pancancer_LONP1",11,4.6); print("1E")

if step in ("all","f2abc"):
    d7 = pd.read_csv(os.path.join(rd,"07_CESC_LONP1_CNA.csv"))
    d8 = pd.read_csv(os.path.join(rd,"08_CESC_gene_panel_expression_RSEM.csv"))
    d8["expr"] = np.log2(d8.LONP1+1)
    m = d7.merge(d8[["sample","expr"]]).dropna(subset=["log2CNA","expr"])
    rho, pv = spearmanr(m.log2CNA, m.expr)
    p = (ggplot(m, aes("log2CNA","expr")) + geom_point(size=1.4, alpha=0.55, color=NPG["navy"])
         + geom_smooth(method="lm", color=NPG["red"], fill=NPG["salmon"], size=0.8)
         + labs(x="LONP1 copy number, log2(CNA ratio)", y="LONP1 mRNA, log2(RSEM+1)", title=f"TCGA-CESC (n={len(m)})")
         + annotate("text", x=m.log2CNA.min()+0.32, y=m.expr.max()-0.1,
                    label=f"Spearman rho = {rho:.2f}\np = {pv:.2e}", size=9, ha="left", family=FAM)
         + T)
    sv(p,"Fig2A_CNA_expression_scatter",3.8,3.8)
    mg = m.dropna(subset=["gistic"]).copy()
    lab = {-2:"Deep del",-1:"Shallow del",0:"Diploid",1:"Gain",2:"Amp"}
    mg["g"] = pd.Categorical(mg.gistic.map(lab), ["Deep del","Shallow del","Diploid","Gain","Amp"])
    kw = kruskal(*[g.expr for _,g in mg.groupby("g", observed=True)])
    p = (ggplot(mg, aes("g","expr",fill="g")) + geom_boxplot(width=0.6, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.15, size=1.0, alpha=0.4)
         + scale_fill_manual(values=[NPG["blue"],NPG["teal"],"#d9d9d9",NPG["salmon"],NPG["red"]])
         + labs(x="", y="LONP1 mRNA, log2(RSEM+1)", title="Expression by copy-number class")
         + annotate("text", x=3, y=mg.expr.max()+0.15, label="Kruskal-Wallis "+pfmt(kw.pvalue), size=9, family=FAM)
         + T + theme(axis_text_x=element_text(rotation=30, ha="right", family=FAM), legend_position="none"))
    sv(p,"Fig2B_expression_by_GISTIC",3.8,3.9)
    d10 = pd.read_csv(os.path.join(rd,"10_CESC_subtype.csv"))
    d8["patient"] = d8["sample"].str[:12]
    ms = d8.merge(d10)
    ms = ms[ms.subtype.isin(["CESC_AdenoCarcinoma","CESC_SquamousCarcinoma"])].copy()
    ms["g"] = pd.Categorical(np.where(ms.subtype=="CESC_AdenoCarcinoma","Adeno","SCC"), ["SCC","Adeno"])
    tt = ttest_ind(ms.loc[ms.g=="Adeno","expr"], ms.loc[ms.g=="SCC","expr"], equal_var=False)
    p = (ggplot(ms, aes("g","expr",fill="g")) + geom_boxplot(width=0.5, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.12, size=1.1, alpha=0.45)
         + scale_fill_manual(values=[NPG["purple"],NPG["salmon"]])
         + scale_x_discrete(labels=[f"SCC\n(n={(ms.g=='SCC').sum()})", f"Adeno\n(n={(ms.g=='Adeno').sum()})"])
         + labs(x="", y="LONP1 mRNA, log2(RSEM+1)", title="Histological subtype")
         + annotate("text", x=1.5, y=ms.expr.max()+0.15, label=pfmt(tt.pvalue), size=10, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig2C_subtype",3.0,3.8); print("2ABC")

if step in ("all","f2de"):
    d2 = pd.read_csv(os.path.join(rd,"02_TCGA_CESC_clinical_LONP1_survival.csv"))
    d2["Tg"] = d2.path_T.astype(str).str.extract(r"^(T[1-4])")[0]
    d2.loc[d2.Tg.isin(["T3","T4"]), "Tg"] = "T3/T4"
    dt = d2.dropna(subset=["Tg","LONP1_log2RSEM"]).copy()
    dt["Tg"] = pd.Categorical(dt.Tg, ["T1","T2","T3/T4"])
    kwt = kruskal(*[g.LONP1_log2RSEM for _,g in dt.groupby("Tg", observed=True)])
    ns = dt.Tg.value_counts().reindex(["T1","T2","T3/T4"])
    p = (ggplot(dt, aes("Tg","LONP1_log2RSEM",fill="Tg")) + geom_boxplot(width=0.55, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.13, size=1.0, alpha=0.45)
         + scale_fill_manual(values=[NPG["blue"],NPG["salmon"],NPG["red"]])
         + scale_x_discrete(labels=[f"T1\n(n={ns['T1']})",f"T2\n(n={ns['T2']})",f"T3/T4\n(n={ns['T3/T4']})"])
         + labs(x="", y="LONP1 mRNA, log2(RSEM+1)", title="Pathological T stage")
         + annotate("text", x=2, y=dt.LONP1_log2RSEM.max()+0.15, label="Kruskal-Wallis "+pfmt(kwt.pvalue), size=9, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig2D_T_stage",3.4,3.8)
    dn = d2[d2.path_N.isin(["N0","N1"])].dropna(subset=["LONP1_log2RSEM"]).copy()
    wN = mannwhitneyu(dn.loc[dn.path_N=="N1","LONP1_log2RSEM"], dn.loc[dn.path_N=="N0","LONP1_log2RSEM"])
    p = (ggplot(dn, aes("path_N","LONP1_log2RSEM",fill="path_N")) + geom_boxplot(width=0.5, outlier_shape="", alpha=0.85, size=0.5)
         + geom_jitter(width=0.12, size=1.0, alpha=0.45)
         + scale_fill_manual(values=[NPG["blue"],NPG["red"]])
         + scale_x_discrete(labels=[f"N0\n(n={(dn.path_N=='N0').sum()})",f"N1\n(n={(dn.path_N=='N1').sum()})"])
         + labs(x="", y="LONP1 mRNA, log2(RSEM+1)", title="Lymph node status")
         + annotate("text", x=1.5, y=dn.LONP1_log2RSEM.max()+0.15, label=pfmt(wN.pvalue), size=10, family=FAM)
         + T + theme(legend_position="none"))
    sv(p,"Fig2E_N_stage",3.0,3.8)
    # 落盘检验口径
    out = dt.groupby("Tg", observed=True).LONP1_log2RSEM.agg(["count","mean","std"]).round(4)
    out.to_csv(os.path.join(rd,"22_clinical_assoc_Tstage.csv"))
    dn.groupby("path_N").LONP1_log2RSEM.agg(["count","mean","std"]).round(4).to_csv(os.path.join(rd,"22_clinical_assoc_Nstage.csv"))
    print("2DE", "T:", pfmt(kwt.pvalue), "N:", pfmt(wN.pvalue))
